USE  customer_behaviour;


# what is the total revenue generated by male vs female customer?
select gender,sum(purchase_amount)as Revenue from customer_shopping_behavior
group by gender
order by Revenue DESC;


# which customer used the discount but still spent more than the average purchase amount?

SELECT customer_id,age,gender,purchase_frequency_days FROM customer_shopping_behavior
WHERE discount_applied ='Yes' 
AND  purchase_amount >= ( 
      SELECT AVG(purchase_amount)
      FROM customer_shopping_behavior
  )
ORDER BY purchase_amount DESC;


#which are the top 5 products with the highest average review rating ?
SELECT
    item_purchased,
    ROUND(AVG(review_rating::numeric),2) AS avg_rating
FROM customer_shopping_behavior
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;


 # Compare the average Purchase amounts between standard and express shipping.

 SELECT shipping_type,AVG(purchase_amount) AS Average_purchase_amount FROM customer_shopping_behavior
 WHERE shipping_type IN ('Standard','Express')
 GROUP BY shipping_type
 ORDER BY Average_purchase_amount DESC;
 

 # Do subscribed customers spend more ?  Compare average spend and total revenue between subscribed and non-subscribed customer
 SELECT subscription_status,
 ROUND(AVG(purchase_amount),2) AS average_spend,
 SUM(purchase_amount) AS total_revenue,
 COUNT(customer_id) AS total_customers
 FROM customer_shopping_behavior
 GROUP BY subscription_status
 ORDER BY total_revenue,average_spend,total_customers ASC;


 # which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased ,    
    ROUND(100* SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/ COUNT(*),2) AS discount_rate
 FROM customer_shopping_behavior
 GROUP BY item_purchased
 ORDER BY discount_rate DESC LIMIT 5; 

 # Segment customers into New, Returning , and Loyal based on their total number of previous purchases , and show the count of each segment .
with customer_type as(
    select customer_id,previous_purchases,
    case 
        when previous_purchases =1 then 'New'
        when previous_purchases between 2 and 10 then 'Returning'
        else 'Loyal' end as customer_segment 
        from customer_shopping_behavior
)
select customer_segment ,  count(*) as "Number of Customers"
from customer_type 
group by customer_segment 


# what are the top3 most purchased products within  each category?
with item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer_shopping_behavior
    GROUP BY category, item_purchased
)
SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;




-- Are Customers who are repeat buyers (more than 5 previous purchases ) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers
from customer_shopping_behavior 
where previous_purchases >= 5
group by subscription_status;



-- What is the revenue contribution of each group 
select age_group, sum(purchase_amount) as revenue 
from customer_shopping_behavior
group by age_group
order by revenue desc ;